### ISSUE TITLE
Herobrine Factions TimeoutException : null

### ISSUE THREAD

**Issue by Cyclonic-Flame** [NeolyteNetwork/Issues#10]
At 11pm (CST) Herobrine Factions crashed and it has not come back online as it normally does.
The error shown after several seconds after attempting to connect reads as "Exception Connecting:ReadTimeoutException : null."
All other locations are up and running so far.

**Comment by Envici** [comment]
I am currently away from my computer. How long has it been down exactly?

**Comment by Cyclonic-Flame** [comment]
It appears to be fixed now. The server seems to have taken a hour to reload
