### ISSUE TITLE
Herobrines Graveyard

### ISSUE THREAD

**Issue by Winter-CrayolaCrayonz** [NeolyteNetwork/Issues#11]
A player has recently gotten himself stuck inside of herobrines graveyard. I am now also stuck there, we cannot run any teleportation commands.

Every 1-2 minutes we keep getting chat spams with messages that say "You cannot teleport while in combat" although we are not pvping. https://gyazo.com/10baaca80fa5ced5f9c66098f18024f8

**Comment by Envici** [comment]
Hasn't happened in a while. Closing issue but I will re-open if the issue arises again :)
