### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Tobolov** [NeolyteNetwork/Issues#12]
on the home page of the website: 

CONNECT AT PLAY.NEOLYTE.NET TO PLAY WITH Failed to connect to MySQL: Can't connect to MySQL server on '213.136.83.115' (111)

**Comment by Envici** [comment]
We are aware and are working on a fix. Thanks for reporting Matt :)

**Comment by Tobolov** [comment]
all good senpai :love_letter:

**Comment by Envici** [comment]
Resolved.

**Comment by Ladous** [comment]
Problem Existing, working on fix.

**Comment by Ladous** [comment]
Resolved
