### ISSUE TITLE
Error conneting to database:Neolyte.net: 6:12 am:help

### ISSUE THREAD

**Issue by Graymunkee** [NeolyteNetwork/Issues#6]
Help when ever I try to connect connect to the server it always tells me "error connecting to database report this bug" how do i fix it or how can you help?

**Comment by InitializingDev** [comment]
This is a problem with our API for UUID's. We can not resolve this problem until the API is back up again (Should be soon). However don't worry this is server side and you do not have to do anything to your client to fix this.

**Comment by Graymunkee** [comment]
Ok thank you

**Comment by Envici** [comment]
This, as far as I am aware has been resolved.
