### ISSUE TITLE
Factions Overclaiming

### ISSUE THREAD

**Issue by Winter-CrayolaCrayonz** [NeolyteNetwork/Issues#8]
This bug is about factions claiming. The Faction I am apart of (Government) is not allowed to overclaim anything. We cannot overclaim even if we have more power than the faction we are trying to claim over of. It's constantly saying that we do not have enough power although we have a lot more power than any other Faction on the server as of now.

**Comment by Envici** [comment]
Not confirmed. Assigned to @FusionDeck

**Comment by Envici** [comment]
Should be fixed ;)
